/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:458b0eda-4c87-4946-bbad-d6baf57e00e3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EE0XYAAPn",
    "aws_user_pools_web_client_id": "2qjkfohpk2ivufmr3s2m26t8mh",
    "oauth": {},
    "aws_user_files_s3_bucket": "plasticoebff2d7f699d4572a37f664c0688a62d212145-prod",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ykb7n6a7szhiznmxrseaqlu25q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-wlhml2padzghfhwqfkojaoaahu",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
